### ISSUE TITLE
No need of multiple if statements

### ISSUE THREAD

**Issue by driptanil** [Ayush-Singh-Code/roll_the_dice#4]
You can directly print the random number instead of using multiple if statements...

**Comment by driptanil** [comment]
I can fix this, please assign this to me, This will help to me to land my first steps towards open-source

**Comment by Ayush-Singh-Code** [comment]
Thanks

**Comment by driptanil** [comment]
I have made the changes, Will I commit and push???
please tell me because this is my first time

**Comment by Ayush-Singh-Code** [comment]
First, you commit and push to your folk repo then make a pull request to my repo

**Comment by driptanil** [comment]
Ok Thank You 
I have created a fork and pushed the code
